[project]
name = "signal-viewer"
version = "0.2.0"
description = "A GUI for working with (biological) signal data."
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "devduck", email = "frederik.kraemer@dev-duck.dev" }
]
dependencies = [
    "attrs>=26.1.0",
    "loguru>=0.7.3",
    "mne>=1.12.0",
    "numexpr>=2.14.1",
    "numpy>=2.4.4",
    "polars[excel]>=1.39.3",
    "pyarrow>=23.0.1",
    "pyopengl>=3.1.10",
    "pyopengl-accelerate>=3.1.10",
    "pyside6>=6.11.0",
    "pywavelets>=1.9.0",
    "scipy>=1.17.1",
    "tables>=3.11.1",
    "wfdb>=4.3.1",
    "scikit-learn>=1.8.0",
    "neurokit2>=0.2.13",
    "pyqtgraph>=0.14.0",
    "pyside-widgets",
    "pyside-config",
    "ts2vg>=1.2.4",
]

# [build-system]
# requires = ["uv_build>=0.11.6,<0.12.0"]
# build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
    "pyinstaller-hooks-contrib>=2026.4",
]

[project.scripts]
signal-viewer = "signal_viewer.start:gui"
sv = "signal_viewer.start:gui"

[tool.uv]
package = true

[tool.uv.sources]
pyside-config = { workspace = true }
pyside-widgets = { workspace = true }
# pyqtgraph = { git = "https://github.com/pyqtgraph/pyqtgraph", rev = "master" }

[tool.uv.workspace]
members = [
    "pyside-widgets",
    "pyside-config",
]
