@echo off
echo Installing uv...
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

echo Done, starting Signal Viewer...
powershell -ExecutionPolicy ByPass -NoProfile -Command "Start-Process -WindowStyle Hidden -FilePath 'uv' -ArgumentList 'run sv'"